### ISSUE TITLE
Please add About

### ISSUE THREAD

**Issue by pcav** [Oslandia/qgis-menu-builder#1]
about metadata is missing, this metadata entry is required. Please add about to metadata.txt.

**Comment by vpicavet** [comment]
From what I read here, there is an "about" keyword in metadata : https://github.com/Oslandia/qgis-menu-builder/blob/master/metadata.txt

What do you refer to ?

**Comment by pcav** [comment]
Now it's there, I'm publishing it.
Thanks.
